name: Update README

on:
  schedule:
    - cron: "0 12 * * *" # ежедневно в 12:00 UTC
  workflow_dispatch: # можно запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Generate README
        run: node generate_readme.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}

      - name: Commit README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README" || true
          git push
